### ISSUE TITLE
Gradle Tasks failed after execution

### ISSUE THREAD

**Issue by JairAviles** [sebaslogen/CleanGUITestArchitecture#14]
Either I execute connectedCheck or connectedAndroidTest, after finishing I always retrieve the following exception 

`Error:(44, 1) Failed to notify task execution listener.
> Cannot run program "adb": error=2, No such file or directory`

It is concerning the task to retrieve Cucumber test reports on Gradle app file configuration. What could I be missing? Maybe I am not executing the tests in a proper manner. Sebas, could you please give me and advice?

Just for the record, I have installed the platform-tools properly. I am not sure if the path /mnt/sdk/cucumber-reports should be modified, though.

**Comment by sebaslogen** [comment]
It looks to be `adb` program in the [gradle task you mentioned](https://github.com/sebaslogen/CleanGUITestArchitecture/blob/master/app/build.gradle#L43).

If you're executing the gradle task from the command line, check that a call to `adb devices` actually executes the program correctly, maybe you don't have it in the path of your system or the user doesn't have execution permissions over the `adb` binary.

Alternatively, you can comment out the whole `gradle.taskGraph.afterTask` block, to ensure the tests run correctly.

**Comment by JairAviles** [comment]
I was forced to uninstall de platform-tools, seems the were not working. After reinstalling wit the latest version and calling to `adb devices` command runs properly. Thank you for your help.
