### ISSUE TITLE
Run specific feature

### ISSUE THREAD

**Issue by yu-t** [sebaslogen/CleanGUITestArchitecture#15]
Is it possible to run a specific feature? If I specify the feature: @CucumberOptions(features = "features/login.feature") it runs all features no matter.

**Comment by sebaslogen** [comment]
Yes but not by file, instead you have to tag a feature in Cucumber by adding the feature tag just before the `Feature` word and run with `./gradlew connectedAndroidTest -Ptags="@my-feature"`

For more info look `Tags` section in the official Cucumber documentation: https://cucumber.io/docs/reference
