### ISSUE TITLE
Cucumber reports are not generated

### ISSUE THREAD

**Issue by JairAviles** [sebaslogen/CleanGUITestArchitecture#16]
After successfully running the tests through the command line using either `./gradlew connectedAndroidTest` or `./gradlew connectedCheck` it is showing on the Android Monitor the print 

> Retrieving Cucumber test report to /xx_myProjectPath_xx/CleanGUITestArchitecture/app/build

However, when I review on the project view the cucumber-reports folder it is empty. I am able to creat the report with spoon abd the default with androidTests, though not the case with cucumber-reports.

![screen shot 2017-05-23 at 09 29 40](https://cloud.githubusercontent.com/assets/178258/26354365/ac89d5fe-3f9a-11e7-9c6f-4c6ddb030ca3.png)

**Comment by JairAviles** [comment]
It seems there is a pending bug to fix since few years ago. What is more, I came across on the internet with other questions in StackOverflow and Google groups and yet, there is no a solution for this situation.

[Google Groups Discussion](https://groups.google.com/forum/#!topic/cukes/q7O1fe95A2g)

**Comment by sebaslogen** [comment]
Another thing you can try is to align the report paths to write to and read from in your phone to a path that matches your project and see if the files are writen in the phone to that folder after running, modify:
https://github.com/sebaslogen/CleanGUITestArchitecture/blob/master/app/src/androidTest/java/com/neoranga55/cleanguitestarchitecture/test/CucumberTestCase.java#L18

https://github.com/sebaslogen/CleanGUITestArchitecture/blob/master/app/build.gradle#L43

**Comment by willpowr** [comment]
Hi,
I've loaded, compiled and run the application successfully in Android Studio 2.3.2. However when I run Feature: defaults I experience a failure with the output below. Any ideas on what's going wrong? Do you require additional files?

Thanks,

H

...
Testing started at 11:54 ...

Undefined step: Given  I can see the Main Activity view

Undefined step: When  I enter the My Microwave Power value

Undefined step: Then  I should be able to save my microwave power value

1 Scenarios (1 undefined)
3 Steps (3 undefined)
0m0.000s


You can implement missing steps with the snippets below:

@Given...

**Comment by JairAviles** [comment]
Hey @sebaslogen sorry for the delay in replying. I did not understand very well your suggestion. You mean to change the format path on CucumberTestCase class and must be same as defined on build.gradle?

**Comment by sebaslogen** [comment]
Yes and check if any file is created on the phone in that folder.

**Comment by JairAviles** [comment]
I changed the path folder in CucumberTestCase class, from [/data/data/com.neoranga55.cleanguitestarchitecture/cucumber-reports/](https://github.com/sebaslogen/CleanGUITestArchitecture/blob/master/app/src/androidTest/java/com/neoranga55/cleanguitestarchitecture/test/CucumberTestCase.java#L18) to 
/mnt/sdcard/cucumber-reports/

However, when running the instrumented tests. Cucumber jvm is not recognizing 

![error1](https://user-images.githubusercontent.com/178258/27037998-145e4dca-4f60-11e7-9e14-3cee04e737a8.png)

On the same way, I also tried changing the path from gradle file. When finishing syn an running it still not creating the cucumber reports and do not create any file on my /data... path on the mobile,

**Comment by sebaslogen** [comment]
@JairAviles  I just submitted a change to align both reporting folders in build.gradle and in CucumberTestCase to /mnt/sdcard/cucumber-reports/ - I executed it on an emulator (Nexus 4 API 21) and it works well. I suggest trying with the latest code and an emulator.

On the other hand, when I tried with the /data/data... I see the folder is created and filled while the tests are being executed but it's deleted just as the test finishes and probably before the gradle task that retrieves the report is executed.

**Comment by vsgopinath** [comment]
HI @JairAviles, I am currently facing this issue on configuring my application.Can you please share the solution how you resolved taking the report from the Phone to your computer. I am using Android 6.0 emulator to run my tests.Do I need to add anything for device's API > 21?
