### ISSUE TITLE
Exception while taking the screenshot

### ISSUE THREAD

**Issue by pawankums** [sebaslogen/CleanGUITestArchitecture#18]
hi, i am getting the below exception while taking the screenshot
java.lang.ClassCastException: android.support.v7.view.ContextThemeWrapper cannot be cast to android.app.Activity

It says the error is in SpoonScreenshotAction getActivity method. I am using the latest commit. Please let me know how to resolve it.

**Comment by sebaslogen** [comment]
This seems to be the same problem as https://github.com/sebaslogen/CleanGUITestArchitecture/issues/12
Have you tried the latest version?

**Comment by pawankums** [comment]
@sebaslogen yes, i was using the latest version. However i was able to resolve the issue later. Thanks for your reply.
