### ISSUE TITLE
Not able to execute only scenarios tagged with particular tag

### ISSUE THREAD

**Issue by shalinbshah** [sebaslogen/CleanGUITestArchitecture#2]
The command below executes all the scenario irrespective of tags provided from console

gradlew connectedAndroidTest -Dtags="~@login,~@login_unit"

**Comment by sebaslogen** [comment]
Indeed it's a bug in the documentation, the correct parameter is '-Ptags="~@login,~@login_unit"' because the property is read in build.gradle as a project property (-P), not as a system property (-D).

I just updated the Readme.
Thanks for opening the bug!
