### ISSUE TITLE
How to run multi step definitions file

### ISSUE THREAD

**Issue by daolq3012** [sebaslogen/CleanGUITestArchitecture#21]
Thank you for share great examples. 
I create 2 file step corresponding to 2 screen (search/result)

But when I run android test It only runs the first file with name sort follows alphabet, the second file not run.

my PR implement: https://github.com/daolq3012/Structure_Android/pull/63

Pls help me resolve this proplem. :bowing_man:

**Comment by sebaslogen** [comment]
Hi,
The problem is that Cucumber does not recognize tests by files or classes but rather by tags, see:
https://github.com/sebaslogen/CleanGUITestArchitecture/issues/17

The solution is basically to declare only one class with @CucumberOptions where you configure Cucumber and point it to the java package where all your glue classes are (classes with @Given/@When/@Then steps), see:
https://github.com/sebaslogen/CleanGUITestArchitecture/blob/master/app/src/androidTest/java/com/neoranga55/cleanguitestarchitecture/test/CucumberTestCase.java

**Comment by daolq3012** [comment]
@sebaslogen Thank for reply 🙇 
But I still can't run your sample by command line 
``./gradlew connectedAndroidTest -Ptags="@login-scenarios"``
This is logcat
```script
Starting 0 tests on Nexus_5X_API_24(AVD) - 7.0
Tests on Nexus_5X_API_24(AVD) - 7.0 failed: Instrumentation run failed due to 'Process crashed.'

com.android.builder.testing.ConnectedDevice > No tests found.[Nexus_5X_API_24(AVD) - 7.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
:app:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///Volumes/DATA/ANDROID/WorkSpace/SeftLearn/CleanGUITestArchitecture/app/build/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
I run test on Android Studio 3.0 canary 7

**Comment by sebaslogen** [comment]
To run on an emulator use the previous commit with different results reporting directory, see: 
https://github.com/sebaslogen/CleanGUITestArchitecture/issues/20

**Comment by daolq3012** [comment]
@sebaslogen 
I have the same problem with https://github.com/sebaslogen/CleanGUITestArchitecture/issues/20 work fine on emulator AP 19 but not run on emulator API 24
But I don't know how to this commit https://github.com/sebaslogen/CleanGUITestArchitecture/commit/6d1abf0bc869c9a1eacaecd6634a44bd476fceb4 help me resolve this problem
Please declare more detail 🙇

**Comment by sebaslogen** [comment]
Take the latest code and replace the contents of CucumberTestCase.java by what you see here:
https://github.com/sebaslogen/CleanGUITestArchitecture/blob/40828645e898dc30f289d0a6b2aeeb94d30f2aa1/app/src/androidTest/java/com/neoranga55/cleanguitestarchitecture/test/CucumberTestCase.java

**Comment by daolq3012** [comment]
It work for me! thank you so much 🙇
