### ISSUE TITLE
plugin in Cucumber runner class are showing attribute undefined. 

### ISSUE THREAD

**Issue by harunpcg** [sebaslogen/CleanGUITestArchitecture#32]
![image](https://user-images.githubusercontent.com/96874529/151572493-4100b7f0-16c8-45ec-a0e4-c95743858ce7.png)

Hi,

While i am adding the plugin, under cucumber options are showing me the attribute undefined. Your help/advise will be appreciated.

package test;

import framework.selenium.support.GlobalEng;
import cucumber.api.Scenario;

import org.junit.AfterClass;
import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import com.cucumber.listener.Reporter;

//this is a cucumber annotation dictating the cucumber runner
@RunWith(Cucumber.class)
//this is how we want the results formatted. The only customizable line, different formats can be added or removed. I�ve included the most common ones for convenience
@CucumberOptions(
		features = "classpath:features"	,
		 glue = {"test"},
		 //plugin = {"html:target/cumber-html-report"},
		plugin = {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"},
		format={
				"pretty", "html:target/results", 
				 "html:target/cucumber-reports/cucumber-pretty",
				"json:target/cucumber.json",
				  "rerun:target/cucumber-reports/rerun.txt"
		}
		, tags = {
			// Write your desire Test Case Annotation Name to Execute the Test.
				//"@Broker_Create_Account_End_To_End"
				//"@Broker_Portal_End_To_End_Testing"
				"@TestCaseB"
				//"@Individual_Configure_Account"
				
		}
		, dryRun = false

		, monochrome = true
		)

//this is an empty class to run with. This needs to remain empty

public class RunCucmberTest {

	@AfterClass
	public static void shutdownDriver(){

		if(GlobalEng.webDriver !=null){
			GlobalEng.webDriver.quit();
			GlobalEng.webDriver = null;
		}
	}
	public void setup() {
		

	}

}

**Comment by sebaslogen** [comment]
The code in this repository is 5+ years old so it's possible that the library and configuration described here doesn't work anymore. Check the latest project and documentation here https://github.com/cucumber/cucumber-android

**Comment by harunpcg** [comment]
> The code in this repository is 5+ years old so it's possible that the library and configuration described here doesn't work anymore. Check the latest project and documentation here https://github.com/cucumber/cucumber-android

I understand this code is old, in that case what library's you are asking me to update ? Please guide me.

**Comment by sebaslogen** [comment]
Follow the link and read the instructions, if you have questions you can ask in that GitHub repository:
https://github.com/cucumber/cucumber-android
