### ISSUE TITLE
Is multiple ActivityInstrumentationTestCase2 possible  to run under this setup?

### ISSUE THREAD

**Issue by cooperkong** [sebaslogen/CleanGUITestArchitecture#5]
Hi 

Thanks for the great example, really appreciated!
Just wondering if you have experienced working with multiple ActivityInstrumentationTestCase2 tests. Because later the StepDef might grow to couple hundreds lines easily with all scenarios.

In your case, what if there more screens after welcome screen, how are you going to handle that?
Can they still work under this setup?

Thanks.

**Comment by sebaslogen** [comment]
Yes, it's a good idea to split tests in different feature files. The
cucumber plugin support this and it just works in this example.

For cucumber there is no distinction between putting the tests on the same
file or different files, so remember to add tags to filter tests in the
future.

**Comment by sebaslogen** [comment]
The answer above is for the original question about feature files.

Using multiple instrumentation classes is not possible in the current
setup. Indeed the step definitions file grows so to avoid having a mess
there I follow these guidelines:
- no logic/ifs in step definitions (except parsing text)
- group and abstract similar/related sentences into a single meaningful
  sentence and use regular expression to help making it flexible (i.e. Press
  button "name")
- all sentences in one place avoids duplication and helps finding/reusing

Good luck

**Comment by cooperkong** [comment]
Thanks for the useful tips 👍 
I think the idea to group related sentences into single reusable/meaningful sentences is really important. These kind of steps should not depend on actual scenarios.
For example: see "text", click on "btnName"
