### ISSUE TITLE
Not a Error but a Question... About Espresso and Cucumber

### ISSUE THREAD

**Issue by HowardSchmaeu** [sebaslogen/CleanGUITestArchitecture#9]
sorry but i don't get is: what is the different between Espresso and Cucumber? is it the same? I'm not a test kind a guy .. so what's happen with the Espresso Test Recorder in Android Studio... where is this for?

Or is both totally different? Can you please explain that in short terms?? 
That would be so nice ... Thank you...

**Comment by sebaslogen** [comment]
The short summary:
- Espresso let's your java test code interact with your Android app like clicking on buttons
- Cucumber let's you write English sentences and then it translates and executes them as test code

More info:
- Espresso: https://google.github.io/android-testing-support-library/docs/espresso/
- Cucumber: https://cucumber.io/

**Comment by HowardSchmaeu** [comment]
OKAY... means Cucumber is like an AddOn for EspressoTests? Can i say it like THAT?? :-D

**Comment by sebaslogen** [comment]
Sure.

**Comment by HowardSchmaeu** [comment]
okay got it... THX!!
